export * from "./parseProduct";
export * from "./removeAccents";
export * from "./getSlug";
export * from "./formatPrice";
export * from "./localStorageKeys";
export * from "./generateRawOrder";
export * from "./whatsappRedirection";
export * from "./saveOrderToLocalStorage";
export * from "./removeOrderFromLocalStorage";
