export const Paths = {
  Home: "/home",
  Products: "/products",
  ProductDetail: "/products/:slug",
  Cart: "/cart",
  Checkout: "/checkout",
  CheckoutSuccess: "success/:orderId",
  AdminLogin: "/admin/login",
  AnyAdmin: "/admin/*",
  AdminDashboard: "dashboard",
  NotFound: "/404",
  getProductDetailPath: (slug: string) => `/products/${slug}`,
  getCheckoutSuccessPath: (orderId: string) => `/checkout/success/${orderId}`,
  getCategoryPath: (slug: string) => `/products?category=${slug}`,
};
