export const RelativeAdminPaths = {
  Login: "login",
  Dashboard: "dashboard",
  ProductsList: "products",
  CreateProduct: "products/create",
  EditProduct: "products/:id",
  OrdersList: "orders",
  OrderDetail: "orders/:id",
};

export const Paths = {
  Home: "/home",
  Products: "/products",
  ProductDetail: "/products/:slug",
  Cart: "/cart",
  Checkout: "/checkout",
  CheckoutSuccess: "success/:orderId",
  AdminLogin: `/admin/${RelativeAdminPaths.Login}`,
  Admin: "/admin",
  AnyAdmin: "/admin/*",
  AdminDashboard: `/admin/${RelativeAdminPaths.Dashboard}`,
  AdminProductsList: `/admin/${RelativeAdminPaths.ProductsList}`,
  AdminCreateProduct: `/admin/${RelativeAdminPaths.CreateProduct}`,
  AdminEditProduct: `/admin/${RelativeAdminPaths.EditProduct}`,
  AdminOrdersList: `/admin/${RelativeAdminPaths.OrdersList}`,
  AdminOrderDetail: `/admin/${RelativeAdminPaths.OrderDetail}`,
  NotFound: "/404",
  getProductDetailPath: (slug: string) => `/products/${slug}`,
  getCheckoutSuccessPath: (orderId: string) => `/checkout/success/${orderId}`,
  getCategoryPath: (slug: string) => `/products?category=${slug}`,
  getAdminOrderDetail: (orderId: string) => `/admin/orders/${orderId}`,
};
